# https://travis-ci.org/
#   "Legacy Services Integration"
#   vs. http://travis-ci.com, no free tier
#   minimum $69/mo for one Container

language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "stable"

script: "npm run ci"

branches:
  only:
    - master
    - develop
